apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: canary-demo-ingress
spec:
  rules:
  - host: canary-demo.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: canary-demo-lb
            port:
              number: 80